### ISSUE TITLE
Need Help. DatabaseError.

### ISSUE THREAD

**Issue by zhyr28** [jgorset/fandjango-example#2]
I try to test fandjango-example, so i create an app in Facebook and deploy all the file to web server. But i got error after app uploaded: relation "fandjango_user" does not exist. The app is here:  http://apps.facebook.com/justatestforfun. 

Thank you.

**Comment by jgorset** [comment]
Hi @zhyr28,

you'll need to synchronize your database in order to install Fandjango:

```
$ python manage.py syncdb
```

I have updated the documentation accordingly. I have also updated it to the latest version of Fandjango, so if you're using v4.x.x you might want to [review the changes](https://github.com/jgorset/fandjango-example/commit/49a423d1926ee424d18ee51bb65251325837f695).

**Comment by zhyr28** [comment]
Thank you for replying. 
I did synchronize, and update the version of fandjango, but i still get the same error. Details:

DatabaseError at /
relation "fandjango_user" does not exist
Request Method: POST
Request URL:    http://empty-stream-1622.herokuapp.com/
Django Version: 1.3.1
Exception Type: DatabaseError
Exception Value:  
relation "fandjango_user" does not exist
Exception Location: /app/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py in execute, line 44
Python Executable:  /app/bin/python
Python Version: 2.7.2
Python Path:  
['/app/fandjangoexample',
 '/app/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg',
 '/app/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg',
 '/app/lib/python27.zip',
 '/app/lib/python2.7',
 '/app/lib/python2.7/plat-linux2',
 '/app/lib/python2.7/lib-tk',
 '/app/lib/python2.7/lib-old',
 '/app/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/app/lib/python2.7/site-packages']

**Comment by jgorset** [comment]
Hm!

Have you followed the walkthrough to the point, or are you using a third-party library like South to handle database migrations?

**Comment by zhyr28** [comment]
When i deploy to web server, i was asked to install South.

**Comment by jgorset** [comment]
I see! In that case, you'll need to run `migrate` instead.

```
$ python manage.py migrate
```

**Comment by zhyr28** [comment]
I use both of them, but still does not work.

**Comment by jgorset** [comment]
That's odd. What's the output of `python manage.py migrate --list`?

**Comment by zhyr28** [comment]
```
fandjango
 (*) 0001_initial
 (*) 0002_auto__add_field_user_facebook_username__add_field_user_hometown__add_f
 (*) 0003_auto__add_field_user_authorized
 (*) 0004_auto__chg_field_user_verified
 (*) 0005_auto__add_field_user_middle_name__add_field_user_timezone__add_field_u
 (*) 0006_auto__del_field_user_relationship_status__del_field_user_locale__del_f
 (*) 0007_auto__add_unique_user_facebook_id
 (*) 0008_auto__del_field_user_verified
 (*) 0009_auto__chg_field_oauthtoken_token
```

**Comment by jgorset** [comment]
Hm. The migrations seem to have run fine. Does the application raise a `DatabaseError` under the development server, too, or is this behavior exclusive to Heroku?

**Comment by zhyr28** [comment]
It is exclusive to Heroku.

**Comment by jgorset** [comment]
Are you sure you've synchronized and migrated the database _on Heroku_?

```
$ heroku run python manage.py syncdb
$ heroku run python manage.py migrate
```
