### ISSUE TITLE
Example template tag usage?

### ISSUE THREAD

**Issue by benjamincburns** [jgorset/fandjango-example#3]
It'd be nice if this example showed off how to use the facebook template tags.

**Comment by jgorset** [comment]
Absolutely. I'll add some examples for template tags as time permits, or be happy to accept a pull request if you beat me to it.

**Comment by benjamincburns** [comment]
I'll add it to my TODO for this weekend, although I originally asked because I wasn't sure how best to utilize them. Further it's been two months since I've read through the source for this. I'll try my best, but please review carefully.

**Comment by jgorset** [comment]
I'm closing some stale issues. :smile:
